name: tglow-gamma
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch
      - git+https://github.com/TrynkaLab/tglow-core.git@bioio-migration
      - clij2-fft
      - RedLionfish
      - cellpose==3.0.8
      - h5py
      - cellprofiler
