#!/usr/bin/env bash
# Assumes this is being called from a scripts folder, will put the nextflow workdir 
# one level up

set -e
 
#-----------------------------------------------------------------------
# Function defintiions

# Creates a string <date>_<hourminute>
timestamp_folder_name() {
  date '+%Y%m%d_%H%M'
}

# Checks if a path is writable
check_writable_path() {
    local path="$1"
    # Check if path exists
    if [ -e "$path" ]; then
        # Path exists, check if writable
        if [ -w "$path" ]; then
            return 0
        else
            echo "❌ Error: Path '$path' exists but is not writable"
            return 1
        fi
    else
        # Path doesn't exist, check if parent directory is writable
        local parent_dir=$(dirname "$path")
        if [ -w "$parent_dir" ]; then
            return 0
        else
            echo "❌ Error: Cannot create directory at '$path'. Parent directory not writable"
            return 1
        fi
    fi
}

# Print usage
usage() {
    echo -e "Usage: $0 <stage|run_pipeline> [-c <file.nf>] [-p <profile>] [-l] -- [nextflow pipeline args]"
    echo -e "<stage|run_pipeline>\t\tThe workflow to run"
    echo -e "-c\t\t\t\t<path/to/config.nf> Nextflow config file for the run"
    echo -e "-p\t\t\t\t<profile> Nextflow profile for the run [local|lsf|lsf_ignore_errors]"
    echo -e "-l\t\t\t\tRun nextflow locally instead of submitting to oversubscribed"
    echo -e "-w\t\t\t\tSet the nextflow work directory (default: ../workdir)"
    echo -e "-q\t\t\t\tSet the queue for the nextflow job (default: oversubscribed)"
    echo -e "-t\t\t\t\tSet the time limit for the nextflow job (hours) (default: 120)"
    echo -e "-g\t\t\t\tSet the LSF group for the nextflow job (default: teamtrynka)"
    echo -e "-- The rest is passed to nextlfow and overrides -c"
    echo -e ""
    echo -e ""
    echo -e "Examples:"
    echo -e "tglow-pipeline enrich -c conf.nf -l"
    echo -e "tglow-pipeline enrich -c conf.nf -- --rn_manifest rn_manifest.tsv --rn_wells A1,B2,C3"
    exit 1
}

#-----------------------------------------------------------------------
#                 Update these for your installation
#-----------------------------------------------------------------------
# Set defaults
SUBMIT=1
WORKDIR="../workdir"

# These control the parameters for the Nextflow job 
QUEUE="oversubscribed"
RUNTIME_LIMIT="120"
GROUP="teamtrynka"
PROFILE="lsf"

prefix="$(timestamp_folder_name)"
mkdir -p logs/${prefix}

# Source your nextflow installation here
module load HGI/common/nextflow/25.04.6
 
export HTTP_PROXY='http://wwwcache.sanger.ac.uk:3128'
export HTTPS_PROXY='http://wwwcache.sanger.ac.uk:3128'
export NXF_OPTS="-Xms14G -Xmx14G -Dnxf.pool.maxThreads=2000"
 
# Set this to true to enable a more fancy logging.
# This fancy logging is a bit funky and designed for interactive sessions!
# Alternatively: tail -f <logfile>  or watch -n 1 tail -10 <logfile> 
# if not suing an interactive session
export NXF_ANSI_LOG=true
 
# General Nextflow variables #
 
# Nextflow version, change depending on installation you use
export NXF_VER=25.04.6
 
# Singularity cache folder to use
# Currently doesn't use signularity, but will do in the future
export NXF_SINGULARITY_CACHEDIR=/lustre/scratch125/humgen/teams_v2/trynka/resources/singularity_cache
 
# Path to nextflow file, MUST BE ABSOLUTE
NF_FILE=/software/teamtrynka/installs/tglow-pipeline/dev/beta/main.nf

#-----------------------------------------------------------------
if [ -z "$1" ]; then
    echo "ERROR: No workflow provided."
    usage
fi

WORKFLOW="$1"
ALLOWED=("stage" "run_pipeline")

if [[ ! " ${ALLOWED[*]} " =~ " ${WORKFLOW} " ]]; then
    echo "❌ ERROR: Invalid workflow '$WORKFLOW'"
    echo "Allowed commands are: ${ALLOWED[*]}"
    exit 1
fi

# Remove first argument so we can parse the rest
shift

while getopts ":c:p:hlw:q:t:g:" opt; do
    case $opt in
        c)
            CONFIG_FILE="$OPTARG"
            ;;
        p)
            PROFILE="$OPTARG"
            ;;
        l)
            SUBMIT=0
            ;;
        w)
            WORKDIR="$OPTARG"
            ;;
        q)
            QUEUE="$OPTARG"
            ;;
        t)
            RUNTIME_LIMIT="$OPTARG"
            ;;
        g)
            GROUP="$OPTARG"
            ;;
        h)
            usage
            CMD="nextflow run ${NF_FILE} --help"
            eval $CMD
            exit 0
            ;;
        \?)
            # Do nothing for invalid options: silently ignore them
            ;;
        :)
            # Option requires an argument, handle error if needed or ignore
            ;;
    esac
done

# Drop all remaining arguments
shift $((OPTIND - 1))

# Check that -c was provided
if [ -z "$CONFIG_FILE" ]; then
    echo "❌ WARN: Missing -c <config.nf> argument"
    #usage
fi

# Check .nf extension
if [[ ! "$CONFIG_FILE" =~ \.config$ ]]; then
    echo "❌ WARN: -c File '$CONFIG_FILE' does not have have .config extension"
    #exit 1
fi

# Check the profiles
#ALLOWED=("local" "lsf" "lsf_ignore_errors")

#if [[ ! " ${ALLOWED[*]} " =~ " ${PROFILE} " ]]; then
#    echo "❌ ERROR: Invalid profile '$PROFILE'"
#   echo "Allowed commands are: ${ALLOWED[*]}"
#    exit 1
#fi

# Check if workdir is writable
if ! check_writable_path "$WORKDIR"; then
    exit 1
fi

# Just to make sure it gets logged correctly
if [ $SUBMIT -eq 0 ]; then
    QUEUE="Running locally"
    RUNTIME_LIMIT="NA"
fi

echo "⬆️  Workflow: $WORKFLOW"
echo "📄 Config file: $CONFIG_FILE"
echo "📒 Logs: logs/${prefix}"
echo "📂 Workdir: $WORKDIR"
echo "🔄 Queue: $QUEUE"
echo "⏱️  Runtime limit: $RUNTIME_LIMIT hours"
echo "👨‍👨‍👧‍👧 Group: $GROUP"
echo "🟠 Arguments: $@"

# Build the nextflow command, in this case, parameters are specified through the config
CMD="nextflow \
-log logs/${prefix}/${WORKFLOW}.nextflow.log \
run ${NF_FILE} \
-profile ${PROFILE} \
-w ${WORKDIR} \
-resume \
-entry ${WORKFLOW} \
-with-report logs/${prefix}/${WORKFLOW}.nextflow.html \
-with-trace logs/${prefix}/${WORKFLOW}.nextflow.trace"

# Add the config if exists
if [ -e "$CONFIG_FILE" ]; then
    CMD="$CMD -c ${CONFIG_FILE}"
fi

# Add the remaining arguments
CMD="$CMD $@"

echo "--------------------------------------------------------------------"
echo $CMD
echo "--------------------------------------------------------------------"
if [ $SUBMIT -eq 0 ]; then
    # This runs the nextflow job locally
    eval $CMD
else
    #-----------------------------------------------------------------------
    #                 Update this for your installation
    #-----------------------------------------------------------------------
    # This submits the nextflow runner to the cluster, in this case LSF, but update
    # this for your cluster configuration
    CMD="bsub -n 1 \
    -G ${GROUP} \
    -M 14000 \
    -q ${QUEUE} \
    -W ${RUNTIME_LIMIT}:00 \
    -R 'span[hosts=1] select[mem>14000] rusage[mem=14000]' \
    -o logs/${prefix}/${WORKFLOW}-%J.out \
    -e logs/${prefix}/${WORKFLOW}-%J.err \
    $CMD"

    eval $CMD
fi
